# This file was generated by GoReleaser. DO NOT EDIT.
cask "devlift" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "0942cdebecf4c1b7d3f914c26618bb083d2cb00704ccde3f6e0cf3df3376aaac"
      url "https://github.com/Regobs/devlift-dist/releases/download/v#{version}/devlift_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6fa31c217956c4c684a6e2740ecc3a1c7cb2b978e5a3b1d630d35b07e3f79f18"
      url "https://github.com/Regobs/devlift-dist/releases/download/v#{version}/devlift_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3cab01e038996200d45f13473ed49e0840cd54b454d8837eb1dd45bb71af7519"
      url "https://github.com/Regobs/devlift-dist/releases/download/v#{version}/devlift_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "74392f9475fa84838ade7a91fc2891b7638bea92f119055289c75444263a0478"
      url "https://github.com/Regobs/devlift-dist/releases/download/v#{version}/devlift_#{version}_linux_arm64.tar.gz"
    end
  end

  name "devlift"
  desc "DevLift command-line tool — OAuth login, service/application listing, and AWS resource provisioning"
  homepage "https://github.com/Regobs/devlift-dist"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devlift"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devlift"]
    end
  end

  # No zap stanza required

end
