# This file was generated by GoReleaser. DO NOT EDIT.
cask "devlift" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "1a9575db2491ec452899a9134f75fd32707dbcb860990b20e1f2f2793092260c"
      url "https://github.com/Regobs/devlift-cli/releases/download/v#{version}/devlift_#{version}_darwin_amd64.tar.gz",
        using: :homebrew_curl,
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
    end
    on_arm do
      sha256 "2b7d340864d9577ed9df2d8c6b476c25dc471223945c64b664778f5ce8473148"
      url "https://github.com/Regobs/devlift-cli/releases/download/v#{version}/devlift_#{version}_darwin_arm64.tar.gz",
        using: :homebrew_curl,
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
    end
  end

  on_linux do
    on_intel do
      sha256 "cfe548f3da03ad249a9dabdd87e5cf527f4ab189603cef0e99ffda82b8e33127"
      url "https://github.com/Regobs/devlift-cli/releases/download/v#{version}/devlift_#{version}_linux_amd64.tar.gz",
        using: :homebrew_curl,
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
    end
    on_arm do
      sha256 "03925357933c578ea5b9af6e9e9bfac627d596aef0241b303bbf458113c8ab44"
      url "https://github.com/Regobs/devlift-cli/releases/download/v#{version}/devlift_#{version}_linux_arm64.tar.gz",
        using: :homebrew_curl,
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}",
        ]
    end
  end

  name "devlift"
  desc "DevLift command-line tool — OAuth login, service/application listing, and AWS resource provisioning"
  homepage "https://github.com/Regobs/devlift-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devlift"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devlift"]
    end
  end

  # No zap stanza required

end
