# This file was generated by GoReleaser. DO NOT EDIT.
cask "devlift" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "6334a26e02ec788903b65199ac0670819599f0d44117a467a1d5a2abe96e033b"
      url "https://github.com/Regobs/devlift-dist/releases/download/v#{version}/devlift_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5dff1f90f61cd162361fc087ea2f79f0b288327404f043e7585faafcfee9d404"
      url "https://github.com/Regobs/devlift-dist/releases/download/v#{version}/devlift_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3c992312d8f641f18bb61178a4d49e2e666229873c54f2b95638720fca53cdab"
      url "https://github.com/Regobs/devlift-dist/releases/download/v#{version}/devlift_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e6256f74a39dc708cda84d8b473cf04bb519ca2b685e2f3f22fe940f605a19ed"
      url "https://github.com/Regobs/devlift-dist/releases/download/v#{version}/devlift_#{version}_linux_arm64.tar.gz"
    end
  end

  name "devlift"
  desc "DevLift command-line tool — OAuth login, service/application listing, and AWS resource provisioning"
  homepage "https://github.com/Regobs/devlift-dist"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devlift"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devlift"]
    end
  end

  # No zap stanza required

end
